{% set name = "kahip" %}
{% set version = "3.15" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/KaHIP/KaHIP/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 20760099370ddf7ecb2f92bfdb727def48f6428001165be6ce504264b9a99a0b
  patches:
    - 0001-install-python-component.patch
build:
  number: 1
  skip: true  # [win]

outputs:
  - name: kahip
    build:
      script: bash ${RECIPE_DIR}/build-kahip.sh
      run_exports:
        - {{ pin_subpackage("kahip", max_pin="x.x.x") }}
      force_use_keys:
        - python

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - metis
      run:
        - {{ mpi }}
        - metis

    test:
      source_files:
        - examples
      commands:
        # main kahip lib exists
        - test -f $PREFIX/lib/libkahip${SHLIB_EXT}
        # 'static' bundle lib is actually shared
        - test -f $PREFIX/lib/libkahip_static${SHLIB_EXT}
        - kaffpa examples/delaunay_n15.graph --k 2 --preconfiguration=strong

  - name: kahip-python
    build:
      script: bash ${RECIPE_DIR}/build-kahip-python.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - python  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
        - python
        - pybind11
        - {{ pin_subpackage('kahip', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('kahip', exact=True) }}

    test:
      commands:
        - "python -c 'import kahip'"

about:
  home: https://kahip.github.io
  summary: 'The graph partitioning framework KaHIP -- Karlsruhe High Quality Partitioning'
  description: |
    KaHIP is a family of graph partitioning programs.
    It includes KaFFPa (Karlsruhe Fast Flow Partitioner),
    which is a multilevel graph partitioning algorithm,
    in its variants Strong, Eco and Fast,
    KaFFPaE (KaFFPaEvolutionary) which is a parallel evolutionary algorithm
    that uses KaFFPa to provide combine and mutation operations,
    as well as KaBaPE which extends the evolutionary algorithm.
    Moreover, specialized techniques are included to partition road networks (Buffoon),
    to output a vertex separator from a given partition
    as well as techniques geared towards the efficient partitioning of social networks.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - extern/argtable3-3.2.2/LICENSE
  doc_url: https://kahip.github.io
  dev_url: https://github.com/KaHIP/KaHIP

extra:
  feedstock-name: kahip
  recipe-maintainers:
    - minrk
